name: 'Lint helm-chart'
description: 'Lints helm-chart'

inputs:
  charts_directory:
    required: false
    type: string
    default: "./"

runs:
  using: "composite"
  
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.10.0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        check-latest: true

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.3.1

    - name: Run chart-testing (lint)
      shell: bash
      run: ct lint --target-branch ${{ github.event.repository.default_branch }} --chart-dirs ${{ inputs.charts_directory }}

